name: 'PEP8 Action'
description: 'Ensure the code quality of a python repository'
inputs:
  arguments:
    description: 'Give arguments to the pycodestyle command.'
    required: false
    default: ''
  token:
    description: 'The commenter bot token'
    required: false
outputs:
  exit-code:
    description: '0: success, 1: fail'
  output:
    description: 'Output of the pycodestyle command. Shows formatting errors.'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'award'
  color: 'gray-dark'
